'use client';

import { X } from 'lucide-react';

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TermsModal({ isOpen, onClose }: TermsModalProps) {
  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div 
        className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-y-auto animate-fadeIn"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="sticky top-0 bg-white border-b border-gray-200 p-4 flex justify-between items-center">
          <h2 className="text-xl font-bold text-gray-800">
            Terms of Use & Important Notice
          </h2>
          <button
            onClick={onClose}
            className="p-1 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <div className="p-6 space-y-4 text-gray-700">
          <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4">
            <p className="font-semibold text-yellow-800">
              ⚠️ Important Notice
            </p>
            <p className="text-sm mt-2">
              This tool is not designed for disrespect or defamation. All outputs are AI-generated for fair, constructive comparison only.
            </p>
          </div>

          <section>
            <h3 className="font-semibold text-lg mb-2">Purpose of This Tool</h3>
            <p className="text-sm leading-relaxed">
              The Competitive Tool Analyzer is designed to help entrepreneurs and product managers understand the competitive landscape of SaaS products. It provides AI-generated insights for educational and strategic planning purposes only.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-lg mb-2">Disclaimer</h3>
            <ul className="list-disc list-inside space-y-2 text-sm">
              <li>All analysis is generated by AI and may not be 100% accurate or complete</li>
              <li>The tool does not provide legal, financial, or professional advice</li>
              <li>Information is provided as-is without guarantee of accuracy</li>
              <li>Results should be verified through your own research</li>
              <li>We are not affiliated with any of the analyzed products or companies</li>
            </ul>
          </section>

          <section>
            <h3 className="font-semibold text-lg mb-2">Fair Use Policy</h3>
            <ul className="list-disc list-inside space-y-2 text-sm">
              <li>Analysis is limited to 3 products per day per user (local restriction)</li>
              <li>This tool is for constructive business analysis only</li>
              <li>Do not use for harassment, defamation, or unfair criticism</li>
              <li>Respect intellectual property rights of analyzed products</li>
            </ul>
          </section>

          <section>
            <h3 className="font-semibold text-lg mb-2">Data Privacy</h3>
            <ul className="list-disc list-inside space-y-2 text-sm">
              <li>We do not store your analysis queries or results</li>
              <li>Usage tracking is anonymous and for rate limiting only</li>
              <li>No personal information is collected or shared</li>
            </ul>
          </section>

          <section>
            <h3 className="font-semibold text-lg mb-2">Limitation of Liability</h3>
            <p className="text-sm leading-relaxed">
              By using this tool, you agree that SaaS RealityCheck and its creators shall not be liable for any damages, losses, or consequences arising from the use of this tool or its generated content. Use at your own risk and judgment.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-lg mb-2">Contact</h3>
            <p className="text-sm">
              For questions, concerns, or feedback about this tool, please contact us through our website.
            </p>
          </section>

          <div className="mt-6 pt-4 border-t border-gray-200 text-center text-xs text-gray-500">
            <p>Copyright © 2025 SaaS RealityCheck</p>
            <p className="mt-1">All rights reserved.</p>
          </div>
        </div>
      </div>
    </div>
  );
}